### ISSUE TITLE
Previous searches in the suggestion box are not recolored.

### ISSUE THREAD

**Issue by NSDex** [stormbreakerbg/Dark-youtube-plugin-chrome#16] opened 2015-09-09 02:47 UTC
Suggestions in the search box that match previous searches are being colored with the default 'visited link' (purple) color.  This looks bad against the dark background of the suggestion box.  

Steps to reproduce:
1) Start entering a search query into the search box on any page
2) Select an item from the suggestions list
3) Start searching for that same query again.

**Comment by NSDex** [comment] 2015-09-09 02:49
It looks like fixing this will not be straightforward.  Y.T. is coloring the text with inline CSS instead of class/identifier names.

**Comment by stormbreakerbg** [comment] 2015-09-09 08:11
I can't reproduce this. I don't get the different color links even on the default design.

**Comment by link07** [comment] 2015-09-09 17:25
I don't see this one either of my machines, though I've only checked the newest version of the plugin.  Perhaps YouTube is doing targeted testing on a new design again?

**Comment by stormbreakerbg** [comment] 2015-09-09 19:00
Yeah, most probably.

Also, `!important` CSS rules override inline styles, we can use this. Unfortunately, we would need something to select them by, maybe something hacky like "li[style]"?

**Comment by NSDex** [comment] 2015-09-10 01:18
Yeah, I'm not seeing this when signed out.  Let's leave this issue open for the next few days and see if things change.

**Comment by chukaluk** [comment] 2015-11-06 15:14
Since the last comment was Sep 9, I'm assuming there hasn't been any progress. This is still an issue. I'm attaching image so it can be clearly seen. 
![ex](https://cloud.githubusercontent.com/assets/7636422/11000313/fb42af56-846e-11e5-8dd0-a6f91d78b758.png)

**Comment by chukaluk** [comment] 2015-11-17 01:43
Looks to be somewhere in here:
![screen shot 2015-11-16 at 8 42 06 pm](https://cloud.githubusercontent.com/assets/7636422/11200268/b1b1b8a0-8ca2-11e5-98a5-a56e6b4d6822.png)

**Comment by chukaluk** [comment] 2015-11-17 01:47
Also, when you go to delete a playlist that you have created, the popup looks like this: 
![screen shot 2015-11-16 at 8 44 48 pm](https://cloud.githubusercontent.com/assets/7636422/11200314/1ca05acc-8ca3-11e5-888f-5c42a03fd99d.png)


And the relevant snippet:
![screen shot 2015-11-16 at 8 45 30 pm](https://cloud.githubusercontent.com/assets/7636422/11200325/2e3b91fc-8ca3-11e5-9b20-53318b91839d.png)

**Comment by link07** [comment] 2015-11-17 03:17
I still do not see the issue with the search bar, though it would annoy me to no end if I did haha.  The image you linked is for the text box (the "input"), not for the dropdown, so it's not super useful.

I did format the playlist menu a bit more though, #18.

**Comment by NSDex** [comment] 2015-11-17 05:33
I'm still seeing this.  But as I mentioned above I'm not sure how it can be fixed since the coloring is being applied with inline CSS:

![image](https://cloud.githubusercontent.com/assets/2069299/11203531/848be83a-8ca9-11e5-8ebf-9d944a3324e0.png)

**Comment by link07** [comment] 2015-11-17 06:08
Hmm, from my own testing, this appears to work.
[img]http://i.imgur.com/k8PaR2K.png[/img]
I'll throw that into #19

**Comment by chukaluk** [comment] 2015-11-19 20:58
Ah, couldn't quite find where the dropdown was nested in. Good looks! Any idea when the next update will hit the store? 

If it's working for you we can mark this solved

**Comment by jcmadrigalg** [comment] 2016-02-17 00:52
Hi,
I can confirm that the issue is still there, it happen when you trying to do a search that match a previews search, like on this sample, I wanted to do a search for the Star Wars trailer.
![image](https://cloud.githubusercontent.com/assets/4017756/13096262/de414026-d4cc-11e5-989d-1689bf0d5dad.png)

I did a quick inspect over the element and it gave me that the color was on this element:
![image](https://cloud.githubusercontent.com/assets/4017756/13096330/801c0ee4-d4cd-11e5-8c1d-f4cc5722b35a.png)

I hope the pictures help.
Have a nice day.

**Comment by link07** [comment] 2016-02-17 05:21
Hey @jcmadrigalg, I'm pretty sure my fix, which I added to #19, will fix your issue.

It has not been yet fixed on the Google Store, @NSDex and @stormbreakerbg appear to have mostly disppeared, and I can't merge my changse (or upload them to the google chrome store).

If you know how to run chrome addons in dev mode, you could download my version and do that.  Let me know if it does fix the issue, as I never actually saw it myself.

**Comment by NSDex** [comment] 2016-02-17 06:09
I'm still here :)

**Closed** 2016-02-17 07:31 UTC

**Comment by stormbreakerbg** [comment] 2016-02-17 07:43
I'm really sorry for not responding in such a long time, thanks for pinging me.

I have merged the PR and uploaded to the stores. Don't hesitate to "poke" me for such things! :)
